# Generated by Django 5.2.1 on 2025-10-11 10:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fach', models.CharField(max_length=200, verbose_name='Fach')),
                ('kurs', models.CharField(max_length=200, verbose_name='Kurs')),
                ('intro', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default='Default text', max_length=200)),
                ('quiz_id', models.CharField(default='Default text', max_length=200)),
                ('item_id', models.CharField(default='Default text', max_length=200)),
                ('fach', models.CharField(default='Default text', max_length=200, verbose_name='Fach')),
                ('kurs', models.CharField(default='Default text', max_length=200, verbose_name='Kurs')),
                ('level', models.CharField(default='Default text', max_length=200, verbose_name='Level')),
                ('text', models.CharField(default='Default text', max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz_images/')),
                ('question', models.CharField(default='Default text', max_length=1000)),
                ('correct_answer', models.CharField(default='Default text', max_length=1000)),
                ('gemini_feedback', models.BooleanField(default=False)),
                ('feedback_prompt', models.CharField(default='Default text', max_length=1000)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stud_answ1', models.CharField(blank=True, default='', max_length=1000)),
                ('feedback1', models.CharField(blank=True, default='', max_length=1000)),
                ('stud_answ2', models.CharField(blank=True, default='', max_length=1000)),
                ('feedback2', models.CharField(blank=True, default='', max_length=1000)),
                ('stud_answ3', models.CharField(blank=True, default='', max_length=1000)),
                ('feedback3', models.CharField(blank=True, default='', max_length=1000)),
                ('item_rating', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Stabile, externe UUID für die Frage', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('fach', models.CharField(max_length=200, verbose_name='Fach')),
                ('kurs', models.CharField(max_length=200, verbose_name='Kurs')),
                ('level', models.CharField(max_length=200, verbose_name='Level')),
                ('text', models.CharField(blank=True, max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz_images/')),
                ('question', models.CharField(blank=True, max_length=1000)),
                ('correct_answer', models.CharField(blank=True, max_length=1000)),
                ('gemini_feedback', models.BooleanField(default=False)),
                ('feedback_prompt', models.CharField(blank=True, max_length=1000)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
