# Generated by Django 5.2.1 on 2025-10-12 07:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fach', models.CharField(max_length=200, verbose_name='Fach')),
                ('kurs', models.CharField(max_length=200, verbose_name='Kurs')),
                ('intro', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='kurs_images/')),
                ('video_url', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('fach', 'kurs'), name='uniq_fach_kurs')],
            },
        ),
        migrations.CreateModel(
            name='Konzepte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('funny', models.CharField(blank=True, max_length=200, null=True)),
                ('video_url', models.CharField(blank=True, max_length=200, null=True)),
                ('definition', models.TextField(blank=True, default='Um was geht es denn?')),
                ('example', models.TextField(blank=True, default='immer ein Beispiel bringen')),
                ('image', models.ImageField(blank=True, null=True, upload_to='concept_images/')),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konzepte', to='myx_stud.kurse')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=200)),
                ('quiz_id', models.CharField(db_index=True, max_length=200)),
                ('item_id', models.CharField(db_index=True, max_length=200)),
                ('fach', models.CharField(blank=True, max_length=200, verbose_name='Fach')),
                ('kurs', models.CharField(blank=True, max_length=200, verbose_name='Kurs')),
                ('konzept', models.CharField(blank=True, max_length=200, verbose_name='Konzept')),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz_images/')),
                ('question', models.TextField(blank=True)),
                ('correct_answer', models.TextField(blank=True)),
                ('gemini_feedback', models.BooleanField(default=False)),
                ('feedback_prompt', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.JSONField(default=list)),
                ('item_rating', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'indexes': [models.Index(fields=['session_id'], name='myx_stud_qu_session_290ca3_idx'), models.Index(fields=['quiz_id'], name='myx_stud_qu_quiz_id_2d27d3_idx'), models.Index(fields=['item_id'], name='myx_stud_qu_item_id_186ed1_idx'), models.Index(fields=['quiz_id', 'item_id'], name='myx_stud_qu_quiz_id_357294_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz_images/')),
                ('question', models.TextField(blank=True)),
                ('correct_answer', models.TextField(blank=True)),
                ('gemini_feedback', models.BooleanField(default=False)),
                ('feedback_prompt', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('konzept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizitems', to='myx_stud.konzepte')),
            ],
        ),
    ]
