# Generated by Django 5.2.1 on 2025-05-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myx_stud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizquestion',
            old_name='created_ast',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='name',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='correct_answer',
            field=models.CharField(default='Default instruction text', max_length=200),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='instruction',
            field=models.CharField(default='Default instruction text', max_length=200),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='item_id',
            field=models.CharField(default='Default instruction text', max_length=200),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='text',
            field=models.CharField(default='Default instruction text', max_length=200),
        ),
    ]
