# Generated by Django 5.2.1 on 2025-10-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myx_stud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionlog',
            name='image',
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='feedback_prompt',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
