# Generated by Django 5.2.1 on 2025-10-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myx_stud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionlog',
            old_name='feedback1_rating',
            new_name='item_rating',
        ),
        migrations.RemoveField(
            model_name='questionlog',
            name='feedback2_rating',
        ),
        migrations.RemoveField(
            model_name='questionlog',
            name='feedback3_rating',
        ),
        migrations.AddField(
            model_name='questionlog',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
