# Generated by Django 5.2.1 on 2025-05-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myx_stud', '0002_rename_created_ast_quizquestion_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='feedback_prompt',
            field=models.CharField(default='Default  text', max_length=200),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='gaol',
            field=models.CharField(default='Default  text', max_length=200),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='topic',
            field=models.CharField(default='Default  text', max_length=200),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_answer',
            field=models.CharField(default='Default  text', max_length=200),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='instruction',
            field=models.CharField(default='Default  text', max_length=200),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='item_id',
            field=models.CharField(default='Default  text', max_length=200),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='text',
            field=models.CharField(default='Default  text', max_length=200),
        ),
    ]
