# Generated by Django 5.2.1 on 2025-10-20 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myx_stud', '0002_remove_questionlog_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kurse',
            name='editors',
            field=models.ManyToManyField(blank=True, help_text='Benutzer mit Redakteursrechten für diesen Kurs.', related_name='editable_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
