# Generated by Django 5.2.1 on 2025-05-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myx_stud', '0003_quizquestion_feedback_prompt_quizquestion_gaol_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizquestion',
            old_name='gaol',
            new_name='goal',
        ),
        migrations.RenameField(
            model_name='quizquestion',
            old_name='instruction',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='done',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
