# Generated by Django 5.2.1 on 2025-06-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myx_stud', '0004_rename_gaol_quizquestion_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='title',
            field=models.CharField(default='Default title', max_length=200),
        ),
    ]
