# Generated by Django 5.2.1 on 2025-06-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myx_stud', '0005_quizquestion_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_answer',
            field=models.CharField(default='Default  text', max_length=1000),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='feedback_prompt',
            field=models.CharField(default='Default  text', max_length=1000),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question',
            field=models.CharField(default='Default  text', max_length=1000),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='text',
            field=models.CharField(default='Default  text', max_length=1000),
        ),
    ]
