# Generated by Django 5.2.1 on 2025-06-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myx_stud', '0007_quizquestion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='gemini_feedback',
            field=models.BooleanField(default=False),
        ),
    ]
