# Generated by Django 5.2.1 on 2025-09-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myx_stud', '0008_quizquestion_gemini_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default='Default text', max_length=200)),
                ('quiz_id', models.CharField(default='Default text', max_length=200)),
                ('item_id', models.CharField(default='Default text', max_length=200)),
                ('topic', models.CharField(default='Default text', max_length=200)),
                ('goal', models.CharField(default='Default text', max_length=200)),
                ('text', models.CharField(default='Default text', max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz_images/')),
                ('question', models.CharField(default='Default text', max_length=1000)),
                ('correct_answer', models.CharField(default='Default text', max_length=1000)),
                ('gemini_feedback', models.BooleanField(default=False)),
                ('feedback_prompt', models.CharField(default='Default text', max_length=1000)),
                ('stud_answ1', models.CharField(blank=True, default='', max_length=1000)),
                ('feedback1', models.CharField(blank=True, default='', max_length=1000)),
                ('feedback1_rating', models.IntegerField(blank=True, null=True)),
                ('stud_answ2', models.CharField(blank=True, default='', max_length=1000)),
                ('feedback2', models.CharField(blank=True, default='', max_length=1000)),
                ('feedback2_rating', models.IntegerField(blank=True, null=True)),
                ('stud_answ3', models.CharField(blank=True, default='', max_length=1000)),
                ('feedback3', models.CharField(blank=True, default='', max_length=1000)),
                ('feedback3_rating', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
